#!/usr/bin/env bash
# demo_01_architecture.sh
# ACES POC Demo — Section 1: Architecture Overview
# Mind Over Metadata LLC © 2026 — Peter Heller
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BOLD='\033[1m'; CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
BLUE='\033[0;34m'; RESET='\033[0m'

banner() {
  echo -e "\n${BOLD}${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
  echo -e "${BOLD}${CYAN}║  $1$(printf '%*s' $((54 - ${#1})) '')║${RESET}"
  echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}\n"
}

section() {
  echo -e "\n${BOLD}${YELLOW}━━━ $1 ━━━${RESET}\n"
}

banner "ACES POC — Section 1: Architecture Overview"
echo -e "${BOLD}Mind Over Metadata LLC — Peter Heller${RESET}"
echo -e "D⁴ MDLC — Domain-Driven Database Design Metadata-Driven Lifecycle\n"

# ── FQSN Taxonomy ─────────────────────────────────────────────────────────────
section "1.1 — FQSN Taxonomy (Fully Qualified Skill Name)"
echo -e "The ACES skill repository follows a three-level BGD hierarchy:"
echo -e ""
echo -e "  ${BOLD}PILLAR/DOMAIN/SKILL_NAME${RESET}"
echo -e ""
echo -e "  ${CYAN}MetaArchitecture/${RESET}     — abstract governance skills"
echo -e "  ${CYAN}CodingArchitecture/${RESET}   — reusable HOW patterns"
echo -e "  ${CYAN}TaskArchitecture/${RESET}     — domain-specific WHAT patterns"
echo ""

# ── Repo structure ────────────────────────────────────────────────────────────
section "1.2 — Repository Structure"
find . -name "system.md" | grep -v ".git\|_archive\|node_modules" | sort | \
  sed 's|^\./||' | \
  awk '{
    split($0, parts, "/")
    indent = ""
    for (i=1; i<length(parts); i++) indent = indent "  "
    print indent "├── " parts[length(parts)-1] "/" parts[length(parts)]
  }'

echo ""
echo -e "  ${GREEN}$(find . -name "system.md" | grep -v ".git\|_archive" | wc -l) system.md files${RESET} (source of truth)"
echo -e "  ${GREEN}$(find . -name "system.yaml" | grep -v ".git\|_archive" | wc -l) system.yaml files${RESET} (derived — YAML behavioral contract)"
echo -e "  ${GREEN}$(find . -name "system.toon" | grep -v ".git\|_archive" | wc -l) system.toon files${RESET} (derived — TOON token-optimized)"

# ── Three-File Standard ───────────────────────────────────────────────────────
section "1.3 — Three-File Skill Standard"
echo -e "Every ACES skill has exactly three artifacts:"
echo ""
echo -e "  ${BOLD}system.md${RESET}    — Human-readable behavioral contract (source of truth)"
echo -e "  ${BOLD}system.yaml${RESET}  — LLM-readable structured form (derived)"
echo -e "  ${BOLD}system.toon${RESET}  — Token-Optimized Object Notation (derived, ~14% smaller)"
echo ""
echo -e "Derived artifacts are generated by ${CYAN}sync_skill.sh${RESET} using:"
echo -e "  fabric --pattern from_system.md_to_system.yaml"
echo -e "  fabric --pattern from_system.md_to_system.toon"

# ── Example skill ─────────────────────────────────────────────────────────────
section "1.4 — Example Skill: ACES_extract_wisdom"
SKILL="CodingArchitecture/FabricStitch/ACES_extract_wisdom"
echo -e "FQSN: ${CYAN}$SKILL${RESET}"
echo ""
echo -e "${BOLD}system.md (first 10 lines):${RESET}"
head -10 "$SKILL/system.md"
echo ""
echo -e "${BOLD}system.yaml (first 8 lines):${RESET}"
head -8 "$SKILL/system.yaml"
echo ""
echo -e "${BOLD}system.toon (first 8 lines):${RESET}"
head -8 "$SKILL/system.toon"

# ── ACES Framework Mapping ────────────────────────────────────────────────────
section "1.5 — ACES Framework Mapping"
echo -e "DEC ACES (1980s)              →  Modern ACES POC"
echo -e "─────────────────────────────────────────────────────"
echo -e "Application Definition Utility →  system.md (TDL)"
echo -e "Task Definition Language       →  sync_skill.sh"
echo -e "Exchange Step                  →  Fabric pattern invocation"
echo -e "Processing Step                →  FabricStitch pipeline step"
echo -e "Execution Controller (EXC)     →  LangGraph orchestration"
echo -e "DECforms                       →  Marimo reactive notebook"
echo -e "Audit trail                    →  cost_audit.log (ADR-009)"

echo ""
echo -e "${GREEN}${BOLD}✓ Section 1 complete${RESET}"
echo ""
read -p "Press Enter for Section 2: Live Sync Pipeline →"
